IMPACT_CLUSTER_SEED_NODES: 192.168.12.101
IMPACT_CLUSTER_USERNAME: cassandra
IMPACT_CLUSTER_PASSWORD: F00theN0ise!
IMPACT_ORG_ID: ach
AIO_IP: 192.168.12.246
AIO_USERNAME: cassandra
AIO_PASSWORD: F00theN0ise!