IMPACT_CLUSTER_SEED_NODES: 192.168.12.101
IMPACT_CLUSTER_USERNAME: cassandra
IMPACT_CLUSTER_PASSWORD: F00theN0ise!
IMPACT_ORG_ID: ach
AIO_IP: 192.168.12.246
AIO_USERNAME: cassandra
AIO_PASSWORD: F00theN0ise!

# Performance tuning parameters (optional - will use defaults if not specified)
MAX_WORKERS: 5              # Number of parallel threads for fetching data (1-10 recommended)
BATCH_INSERT_SIZE: 50       # Number of rows to insert in a single batch (10-100 recommended)
FETCH_BATCH_SIZE: 100       # Number of rows to process before taking a small break (50-500 recommended)